name = "hono-workers-template"
compatibility_date = "2023-12-01"
#node_compat = true
main = "src/index.ts"
# [vars]
# MY_VARIABLE = "production_value"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[[r2_buckets]]
binding = "BUCKET" # i.e. available in your Worker on env.BUCKET
bucket_name = "shopping-bucket"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "shopping-db"
database_id = "62664d60-cf7b-4f97-ad50-0c8dc0227a0a"



